name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Build
      run: go build -v

    - name: Test
      run: go test -v ./...

    - name: gorgeous style check
      run: go install github.com/fsgo/go_fmt/cmd/gorgeous@latest && gorgeous -d ./...
      
    - name: staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest && staticcheck ./...
